apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f96rhdoyn-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:3e16082feadacd725bcf05c1e304562c9635479a@sha256:540800ea28e6eb37c06b33d3bfe6ce0b5067bc1387f40fc4e0cf43c27520d72c
          name: container-image
