apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f96rhdoyn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f96rhdoyn-go 
  name: f96rhdoyn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f96rhdoyn-go 
